name: ubereats_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  internet_connection_checker_plus: ^2.5.2
  logging: ^1.2.0
  dartz: ^0.10.1
  connectivity_plus: ^6.0.5
  http: ^1.2.2
  permission_handler: ^11.3.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/translations/
    - assets/jsons/
    - assets/img/

  fonts:
    - family: UberMove
      fonts:
        - asset: assets/fonts/UberMove-Bold.ttf
        - asset: assets/fonts/UberMove-Light.ttf
        - asset: assets/fonts/UberMove-Medium.ttf
        - asset: assets/fonts/UberMove-Regular.ttf